branches:
    only:
        - master

stages:
    - build
    - name: doc
      if: type = push

matrix:
    include:
        - language: cpp
          stage: build
          compiler: g++
          sudo: true
          services:
              - docker
          install: docker pull $DOCKER_AUX_REPO
          script:
              - mkdir build
              - cd build
              - docker run -v $TRAVIS_BUILD_DIR:$TRAVIS_BUILD_DIR -w $PWD $DOCKER_AUX_REPO cmake -DREPORT_COVERAGE=ON ../
              - docker run -v $TRAVIS_BUILD_DIR:$TRAVIS_BUILD_DIR -w $PWD $DOCKER_AUX_REPO make -j2
              - docker run -v $TRAVIS_BUILD_DIR:$TRAVIS_BUILD_DIR -w $PWD $DOCKER_AUX_REPO make test
          after_success:
              - docker run $(bash <(curl -s https://codecov.io/env)) -v $TRAVIS_BUILD_DIR:$TRAVIS_BUILD_DIR -w $PWD $DOCKER_AUX_REPO bash -c "bash <(curl -s https://codecov.io/bash)"

        - language: cpp
          stage: doc
          addons:
              apt:
                  packages:
                      doxygen
          script:
              - cd docs
              - bash genAndDeploy.sh

